on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/*'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '*.md'

name: "Build Dev"
jobs:
  build:
    name: Build Dev
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # https://github.com/subosito/flutter-action/issues/278
      # - name: Export pub environment variable
      #   run: |
      #     if [ "$RUNNER_OS" == "Windows" ]; then
      #       echo "PUB_CACHE=$LOCALAPPDATA\\Pub\\Cache" >> $GITHUB_ENV
      #     fi
      #   shell: bash
    
      - run: echo "NEW_VERSION=${{ github.ref_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Bump MyAppVersion in Inno Setup
        run: |
          (Get-Content -Path "inno-setup.iss" -Encoding utf8BOM) -replace '#define MyAppVersion "[\d\.]+"', "#define MyAppVersion `"${{ env.NEW_VERSION }}`"" | Set-Content -Path "inno-setup.iss" -Encoding utf8BOM
        shell: pwsh
      
      - name: Compile C code
        run: gcc -shared -o process_checker.dll process_checker.c -lpsapi -O3
        working-directory: native_utils
      
      - run: flutter gen-l10n
        working-directory: src
        
      - run: dart run build_runner build --delete-conflicting-outputs
        working-directory: src
        
      - name: Build revitool CLI
        run: dart compile exe src/lib/main_cli.dart -o revitool.exe --define=APP_VERSION=${{ env.NEW_VERSION }} 

      - name: Enable Administrator Privileges for revitool CLI app
        shell: pwsh
        run: |
          & "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.22621.0\x64\mt.exe" -nologo -manifest src/windows/app.manifest -outputresource:revitool.exe;1

      - name: Build revitool GUI
        run: flutter build windows --build-name=${{ env.NEW_VERSION }} --build-number=1 --obfuscate --split-debug-info=/symbols --dart-define=APP_VERSION=${{ env.NEW_VERSION }}
        working-directory: src
      
      - name: Build Installer
        run: |
          curl.exe -sSL "https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/raw/main/ChineseSimplified.isl" -o "%programfiles(x86)%\Inno Setup 6\Languages\ChineseSimplified.isl"
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "inno-setup.iss"
        shell: cmd

      - name: Calculate SHA256 hash
        run: |
          $hash = Get-FileHash "XRSYSHub-Setup.exe" -Algorithm SHA256
          echo "SHA256_HASH=$($hash.Hash)" | Out-File -FilePath $env:GITHUB_ENV -Append
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SHA256_HASH }}
          path: XRSYSHub-Setup.exe