on:
  push:
    tags:
      - '*'
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false

      # https://github.com/subosito/flutter-action/issues/278
      - name: Export pub environment variable
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "PUB_CACHE=$LOCALAPPDATA\\Pub\\Cache" >> $GITHUB_ENV
          fi
        shell: bash
    
      - run: echo "NEW_VERSION=${{ github.ref_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Bump MyAppVersion in Inno Setup
        run: |
          (Get-Content -Path "inno-setup.iss" -Encoding utf8BOM) -replace '#define MyAppVersion "[\d\.]+"', "#define MyAppVersion `"${{ env.NEW_VERSION }}`"" | Set-Content -Path "inno-setup.iss" -Encoding utf8BOM
        shell: pwsh
      
      - run: flutter gen-l10n

      - run: dart run build_runner build --delete-conflicting-outputs

      - run: flutter build windows --build-name=${{ env.NEW_VERSION }} --build-number=1
      
      - name: Build Installer
        run: |
          curl.exe -sSL "https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/raw/main/ChineseSimplified.isl" -o "%programfiles(x86)%\Inno Setup 6\Languages\ChineseSimplified.isl"
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "inno-setup.iss"
        shell: cmd

      - name: Calculate SHA256 hash
        run: |
          $hash = Get-FileHash "build/XRSYSHub-Setup.exe" -Algorithm SHA256
          echo "SHA256_HASH=$($hash.Hash)" | Out-File -FilePath $env:GITHUB_ENV -Append
        
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: build/XRSYSHub-Setup.exe
          asset_name: XRSYSHub-Setup.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "SHA256: `${{ env.SHA256_HASH }}`"
